version: '24.0.7'
services:
  app:
   build: .
   ports:
     - "8080:8080"
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet
     - SPRING_DATASOURCE_USERNAME=wallets
     - SPRING_DATASOURCE_PASSWORD=pass
   depends_on:
     - db

  db:
    image: postgres:13
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=wallets
      - POSTGRES_PASSWORD=pass