version: '24.0.7'
services:

  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wallet
      - POSTGRES_USER=wallets
      - POSTGRES_PASSWORD=pass

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_NAME=wallet
      - POSTGRES_USER=wallets
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432